openapi: 3.0.3
info:
  title: Twitter Process API
  version: '1.0'
  description: |2+


    Created at 27/06/2022, 07:08

    ****


    The self-contained process solution contains

    * The process model as BPMN (auto-deployed during startup)
    * Glue code for the service task
    * REST endpoint that then starts a process instance
    * Test case

    Requirements:

    * Java >= 8
    * Maven

    ## How to run

    * Download/clone the code in this folder.
    * You need to set your Camunda cloud client connection details in the file `application.properties`. Simply replace the existing sample values.
    * Run the application:

    ```
    mvn package exec:java
    ```

    ```
    curl -i -X PUT http://localhost:8323/tweet \
      -H 'cache-control: no-cache' \
      -H 'content-type: application/json' \
      -d '{
      "tweet":"What the f***!",
      "author":"Sergey",
      "boss":"Putin"
    }'
    ```

    * You should see something like this:


paths:
  /process/twitterDemoProcess/TwitterDemoP:
    head:
      tags:
      - twitterDemoProcess
      summary: 'Process: twitterDemoProcess'
      description: This runs the Twitter Approvement Process.
      operationId: 'Process: twitterDemoProcess'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tweet'
            examples:
              twitterDemoProcess:
                value:
                  tweet: Hello Tweet
                  author: pme123
                  boss: Great Master
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewedTweet'
              examples:
                twitterDemoProcess:
                  value:
                    tweet: Hello Tweet
                    author: pme123
                    boss: Great Master
                    approved: false
  /usertask/twitterDemoProcess/user_task_review_tweet:
    head:
      tags:
      - twitterDemoProcess
      summary: 'UserTask: reviewTweetApprovedUT'
      description: '-'
      operationId: 'UserTask: reviewTweetApprovedUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tweet'
            examples:
              reviewTweetApprovedUT:
                value:
                  tweet: Hello Tweet
                  author: pme123
                  boss: Great Master
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewedTweet'
              examples:
                Tweet accepted:
                  value:
                    tweet: Hello Tweet
                    author: pme123
                    boss: Great Master
                    approved: false
                Tweet rejected:
                  value:
                    tweet: Hello Tweet
                    author: pme123
                    boss: Great Master
                    approved: false
components:
  schemas:
    ReviewedTweet:
      required:
      - tweet
      - author
      - boss
      - approved
      type: object
      properties:
        tweet:
          type: string
        author:
          type: string
        boss:
          type: string
        approved:
          type: boolean
      description: Every Tweet has to be accepted by the Boss.
    Tweet:
      required:
      - tweet
      - author
      - boss
      type: object
      properties:
        tweet:
          type: string
        author:
          type: string
        boss:
          type: string
      description: Every employee may create a Tweet.
