openapi: 3.0.3
info:
  title: Demos Example Process API
  version: '1.0'
  summary: |2+


    Created at 09/07/2023, 12:56

    ****




    # Changelog

    <details>
    <summary>CHANGELOG.md</summary>
    <p>


    All notable changes to this project will be documented in this file.

    * Types of Changes (L3):
      * Added: new features
      * Changed: changes in existing functionality
      * Deprecated: soon-to-be-removed features
      * Removed: now removed features
      * Fixed: any bug fixes
      * Security: in case of vulnerabilities


    The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
    and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

    ### Unreleased
    Initial Version

    </p>
    </details>

paths:
  /decisiondmn//singleEntry:
    head:
      tags:
      - ''
      summary: 'DecisionDmn: singleEntry'
      description: |2+


        - Input:  `camundala.examples.demos.DecisionResultTypes > Input`
        - Output: `camundala.bpmn.SingleEntry`



        <div class="diagramCanvas">
          <div class="diagram" id="DecisionResultTypes-35988">
            <img onLoad="openFromUrl('DecisionResultTypes.dmn', new DmnJS({ container: $('#DecisionResultTypes-35988'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [DecisionResultTypes.dmn](src/main/resources/DecisionResultTypes.dmn)

      operationId: 'DecisionDmn: singleEntry'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              singleEntry:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                - type: integer
                  format: int32
              examples:
                singleEntry:
                  value: 1
  /decisiondmn//collectEntries:
    head:
      tags:
      - ''
      summary: 'DecisionDmn: collectEntries'
      description: |2+


        - Input:  `camundala.examples.demos.DecisionResultTypes > Input`
        - Output: `camundala.bpmn.CollectEntries`



        <div class="diagramCanvas">
          <div class="diagram" id="DecisionResultTypes-41962">
            <img onLoad="openFromUrl('DecisionResultTypes.dmn', new DmnJS({ container: $('#DecisionResultTypes-41962'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [DecisionResultTypes.dmn](src/main/resources/DecisionResultTypes.dmn)

      operationId: 'DecisionDmn: collectEntries'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              collectEntries:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                - type: integer
                  format: int32
              examples:
                collectEntries:
                  value:
                  - 1
                  - 2
  /decisiondmn//singleResult:
    head:
      tags:
      - ''
      summary: 'DecisionDmn: singleResult'
      description: |2+


        - Input:  `camundala.examples.demos.DecisionResultTypes > Input`
        - Output: `camundala.bpmn.SingleResult`



        <div class="diagramCanvas">
          <div class="diagram" id="DecisionResultTypes-91895">
            <img onLoad="openFromUrl('DecisionResultTypes.dmn', new DmnJS({ container: $('#DecisionResultTypes-91895'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [DecisionResultTypes.dmn](src/main/resources/DecisionResultTypes.dmn)

      operationId: 'DecisionDmn: singleResult'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              singleResult:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleResult_camundala.examples.demos.DecisionResultTypes.ManyOutResult[]'
              examples:
                singleResult:
                  value:
                    index: 1
                    emoji: ðŸ¤©
  /decisiondmn//resultList:
    head:
      tags:
      - ''
      summary: 'DecisionDmn: resultList'
      description: |2+


        - Input:  `camundala.examples.demos.DecisionResultTypes > Input`
        - Output: `camundala.bpmn.ResultList`



        <div class="diagramCanvas">
          <div class="diagram" id="DecisionResultTypes-53559">
            <img onLoad="openFromUrl('DecisionResultTypes.dmn', new DmnJS({ container: $('#DecisionResultTypes-53559'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [DecisionResultTypes.dmn](src/main/resources/DecisionResultTypes.dmn)

      operationId: 'DecisionDmn: resultList'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              resultList:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultList_camundala.examples.demos.DecisionResultTypes.ManyOutResult[]'
              examples:
                resultList:
                  value:
                  - index: 1
                    emoji: ðŸ¤©
                  - index: 2
                    emoji: ðŸ˜‚
  /process/camundala-mapping-example:
    head:
      tags:
      - camundala-mapping-example
      summary: 'Process: camundala-mapping-example'
      description: |2+


        - Input:  `camundala.bpmn.NoInput`
        - Output: `camundala.bpmn.NoOutput`



        <div class="diagramCanvas">
          <div class="diagram" id="mapping-example-80500">
            <img onLoad="openFromUrl('mapping-example.bpmn', new BpmnJS({ container: $('#mapping-example-80500'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [mapping-example.bpmn](src/main/resources/mapping-example.bpmn)

      operationId: 'Process: camundala-mapping-example'
      responses:
        '200':
          description: ''
  /decisiondmn/camundala-mapping-example/singleEntry:
    head:
      tags:
      - camundala-mapping-example
      summary: 'DecisionDmn: singleEntry'
      description: |2+


        - Input:  `camundala.examples.demos.DecisionResultTypes > Input`
        - Output: `camundala.bpmn.SingleEntry`



        <div class="diagramCanvas">
          <div class="diagram" id="DecisionResultTypes-57657">
            <img onLoad="openFromUrl('DecisionResultTypes.dmn', new DmnJS({ container: $('#DecisionResultTypes-57657'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [DecisionResultTypes.dmn](src/main/resources/DecisionResultTypes.dmn)

      operationId: 'DecisionDmn: singleEntry'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              singleEntry:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                - type: integer
                  format: int32
              examples:
                singleEntry:
                  value: 1
  /decisiondmn/camundala-mapping-example/collectEntries:
    head:
      tags:
      - camundala-mapping-example
      summary: 'DecisionDmn: collectEntries'
      description: |2+


        - Input:  `camundala.examples.demos.DecisionResultTypes > Input`
        - Output: `camundala.bpmn.CollectEntries`



        <div class="diagramCanvas">
          <div class="diagram" id="DecisionResultTypes-16342">
            <img onLoad="openFromUrl('DecisionResultTypes.dmn', new DmnJS({ container: $('#DecisionResultTypes-16342'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [DecisionResultTypes.dmn](src/main/resources/DecisionResultTypes.dmn)

      operationId: 'DecisionDmn: collectEntries'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              collectEntries:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                - type: integer
                  format: int32
              examples:
                collectEntries:
                  value:
                  - 1
                  - 2
  /decisiondmn/camundala-mapping-example/singleResult:
    head:
      tags:
      - camundala-mapping-example
      summary: 'DecisionDmn: singleResult'
      description: |2+


        - Input:  `camundala.examples.demos.DecisionResultTypes > Input`
        - Output: `camundala.bpmn.SingleResult`



        <div class="diagramCanvas">
          <div class="diagram" id="DecisionResultTypes-74579">
            <img onLoad="openFromUrl('DecisionResultTypes.dmn', new DmnJS({ container: $('#DecisionResultTypes-74579'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [DecisionResultTypes.dmn](src/main/resources/DecisionResultTypes.dmn)

      operationId: 'DecisionDmn: singleResult'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              singleResult:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleResult_camundala.examples.demos.DecisionResultTypes.ManyOutResult[]'
              examples:
                singleResult:
                  value:
                    index: 1
                    emoji: ðŸ¤©
  /decisiondmn/camundala-mapping-example/resultList:
    head:
      tags:
      - camundala-mapping-example
      summary: 'DecisionDmn: resultList'
      description: |2+


        - Input:  `camundala.examples.demos.DecisionResultTypes > Input`
        - Output: `camundala.bpmn.ResultList`



        <div class="diagramCanvas">
          <div class="diagram" id="DecisionResultTypes-73579">
            <img onLoad="openFromUrl('DecisionResultTypes.dmn', new DmnJS({ container: $('#DecisionResultTypes-73579'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [DecisionResultTypes.dmn](src/main/resources/DecisionResultTypes.dmn)

      operationId: 'DecisionDmn: resultList'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              resultList:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultList_camundala.examples.demos.DecisionResultTypes.ManyOutResult[]'
              examples:
                resultList:
                  value:
                  - index: 1
                    emoji: ðŸ¤©
                  - index: 2
                    emoji: ðŸ˜‚
  /process/enum-example:
    head:
      tags:
      - enum-example
      summary: 'Process: enum-example'
      description: |2+


        - Input:  `camundala.examples.demos.EnumExample > Input > A`
        - Output: `camundala.examples.demos.EnumExample > Output > A`



        <div class="diagramCanvas">
          <div class="diagram" id="enum-example-84346">
            <img onLoad="openFromUrl('enum-example.bpmn', new BpmnJS({ container: $('#enum-example-84346'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [enum-example.bpmn](src/main/resources/enum-example.bpmn)

      operationId: 'Process: enum-example'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input1'
            examples:
              enum-example:
                value:
                  someValue: hello
                  simpleEnum: One
                  customMock:
                    someOut: hello
                    intValue: 12
                    simpleEnum: One
                    type: A
                  type: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Output'
              examples:
                enum-example:
                  value:
                    someOut: hello
                    intValue: 12
                    simpleEnum: One
                    type: A
  /decisiondmn//DateExample:
    head:
      tags:
      - ''
      summary: 'DecisionDmn: DateExample'
      description: |2+


        - Input:  `camundala.examples.demos.DateExample > Input`
        - Output: `camundala.bpmn.SingleEntry`



        <div class="diagramCanvas">
          <div class="diagram" id="DateExample-83657">
            <img onLoad="openFromUrl('DateExample.dmn', new DmnJS({ container: $('#DateExample-83657'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [DateExample.dmn](src/main/resources/DateExample.dmn)

      operationId: 'DecisionDmn: DateExample'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input2'
            examples:
              DateExample:
                value:
                  inDate: '2013-12-12T12:12:12'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                - type: string
              examples:
                DateExample:
                  value: 2012-12-12T12:12:12.000+0100
  /decisiondmn//VariablesExample:
    head:
      tags:
      - ''
      summary: 'DecisionDmn: VariablesExample'
      description: |2+


        - Input:  `camundala.examples.demos.VariablesExample > Input`
        - Output: `camundala.bpmn.SingleEntry`



        <div class="diagramCanvas">
          <div class="diagram" id="VariablesExample-73353">
            <img onLoad="openFromUrl('VariablesExample.dmn', new DmnJS({ container: $('#VariablesExample-73353'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [VariablesExample.dmn](src/main/resources/VariablesExample.dmn)

      operationId: 'DecisionDmn: VariablesExample'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input3'
            examples:
              VariablesExample:
                value:
                  letters: A_dynamic_2
                  inputVariable: dynamic
                  outputVariable: dynamicOut
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                - type: string
              examples:
                VariablesExample:
                  value: OK dynamicOut
  /process/simulation-TestOverrides:
    head:
      tags:
      - simulation-TestOverrides
      summary: 'Process: simulation-TestOverrides'
      description: |2+


        - Input:  `camundala.examples.demos.SimulationTestOverridesExample > InOutput`
        - Output: `camundala.examples.demos.SimulationTestOverridesExample > InOutput`



        <div class="diagramCanvas">
          <div class="diagram" id="simulation-TestOverrides-78364">
            <img onLoad="openFromUrl('simulation-TestOverrides.bpmn', new BpmnJS({ container: $('#simulation-TestOverrides-78364'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [simulation-TestOverrides.bpmn](src/main/resources/simulation-TestOverrides.bpmn)

      operationId: 'Process: simulation-TestOverrides'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InOutput'
            examples:
              simulation-TestOverrides:
                value:
                  simpleValue: hello
                  collectionValue:
                  - hello
                  - bye
                  objectValue:
                    name: salu
                    other: false
                  objectCollectionValue:
                  - name: salu
                    other: false
                  - name: tschau
                    other: true
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InOutput'
              examples:
                simulation-TestOverrides:
                  value:
                    simpleValue: hello
                    collectionValue:
                    - hello
                    - bye
                    objectValue:
                      name: salu
                      other: false
                    objectCollectionValue:
                    - name: salu
                      other: false
                    - name: tschau
                      other: true
  /process/SignalMessageExample/signal-example:
    head:
      tags:
      - SignalMessageExample
      summary: 'Process: signal-example'
      description: |2+


        - Input:  `camundala.examples.demos.SignalMessageExample > SignalMessageExampleIn`
        - Output: `camundala.examples.demos.SignalMessageExample > SignalMessageExampleOut`



        <div class="diagramCanvas">
          <div class="diagram" id="signal-example-40856">
            <img onLoad="openFromUrl('signal-example.bpmn', new BpmnJS({ container: $('#signal-example-40856'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [signal-example.bpmn](src/main/resources/signal-example.bpmn)

      operationId: 'Process: signal-example'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignalMessageExampleIn'
            examples:
              signal-example:
                value:
                  someValue: hello
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignalMessageExampleOut'
              examples:
                signal-example:
                  value:
                    someValue: hello
                    endStatus: signalReceived
  /process/SignalMessageExample/message-for-example:
    head:
      tags:
      - SignalMessageExample
      summary: 'Process: message-for-example'
      description: |2+


        - Input:  `camundala.examples.demos.SignalMessageExample > SignalMessageExampleIn`
        - Output: `camundala.examples.demos.SignalMessageExample > SignalMessageExampleOut`



        <div class="diagramCanvas">
          <div class="diagram" id="message-for-example-8646">
            <img onLoad="openFromUrl('message-for-example.bpmn', new BpmnJS({ container: $('#message-for-example-8646'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [message-for-example.bpmn](src/main/resources/message-for-example.bpmn)

      operationId: 'Process: message-for-example'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignalMessageExampleIn'
            examples:
              message-for-example:
                value:
                  someValue: hello
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignalMessageExampleOut'
              examples:
                message-for-example:
                  value:
                    someValue: hello
                    endStatus: messageReceived
  /signalevent/SignalMessageExample/intermediate-signal-for-example:
    head:
      tags:
      - SignalMessageExample
      summary: 'SignalEvent: intermediate-signal-for-example'
      description: |
        - _messageName_: `intermediate-signal-for-example`

        - Input:  `camundala.examples.demos.SignalMessageExample > SignalMessageExampleIn`
        - Output: `camundala.bpmn.NoOutput`
      operationId: 'SignalEvent: intermediate-signal-for-example'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignalMessageExampleIn'
            examples:
              intermediate-signal-for-example:
                value:
                  someValue: hello
        required: true
      responses:
        '200':
          description: ''
  /messageevent/SignalMessageExample/intermediate-message-for-example:
    head:
      tags:
      - SignalMessageExample
      summary: 'MessageEvent: intermediate-message-for-example'
      description: |
        - _messageName_: `intermediate-message-for-example`

        - Input:  `camundala.examples.demos.SignalMessageExample > SignalMessageExampleIn`
        - Output: `camundala.bpmn.NoOutput`
      operationId: 'MessageEvent: intermediate-message-for-example'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignalMessageExampleIn'
            examples:
              intermediate-message-for-example:
                value:
                  someValue: hello
        required: true
      responses:
        '200':
          description: ''
  /process/timer-example:
    head:
      tags:
      - timer-example
      summary: 'Process: timer-example'
      description: |2+


        - Input:  `camundala.bpmn.NoInput`
        - Output: `camundala.bpmn.NoOutput`



        <div class="diagramCanvas">
          <div class="diagram" id="timer-example-28312">
            <img onLoad="openFromUrl('timer-example.bpmn', new BpmnJS({ container: $('#timer-example-28312'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [timer-example.bpmn](src/main/resources/timer-example.bpmn)

      operationId: 'Process: timer-example'
      responses:
        '200':
          description: ''
  /timerevent/timer-example/wait%20for%20one%20day:
    head:
      tags:
      - timer-example
      summary: 'TimerEvent: wait for one day'
      description: |2


        - Input:  `camundala.bpmn.NoInput`
        - Output: `camundala.bpmn.NoOutput`
      operationId: 'TimerEvent: wait for one day'
      responses:
        '200':
          description: ''
components:
  schemas:
    A:
      required:
      - simpleEnum
      type: object
      properties:
        someValue:
          type: string
        simpleEnum:
          $ref: '#/components/schemas/SimpleEnum'
        customMock:
          $ref: '#/components/schemas/Output'
    A1:
      required:
      - intValue
      - simpleEnum
      type: object
      properties:
        someOut:
          type: string
        intValue:
          type: integer
          format: int32
        simpleEnum:
          $ref: '#/components/schemas/SimpleEnum'
    EndStatus:
      oneOf:
      - $ref: '#/components/schemas/messageReceived'
      - $ref: '#/components/schemas/signalReceived'
    InOutput:
      required:
      - simpleValue
      - objectValue
      type: object
      properties:
        simpleValue:
          type: string
        collectionValue:
          type: array
          items:
            type: string
        objectValue:
          $ref: '#/components/schemas/SimpleObject'
        objectCollectionValue:
          type: array
          items:
            $ref: '#/components/schemas/SimpleObject'
    Input:
      required:
      - letter
      type: object
      properties:
        letter:
          type: string
    Input1:
      oneOf:
      - $ref: '#/components/schemas/A'
    Input2:
      required:
      - inDate
      type: object
      properties:
        inDate:
          type: string
    Input3:
      required:
      - inputVariable
      - outputVariable
      type: object
      properties:
        letters:
          type: string
        inputVariable:
          oneOf:
          - type: string
        outputVariable:
          oneOf:
          - type: string
    ManyOutResult:
      required:
      - index
      - emoji
      type: object
      properties:
        index:
          type: integer
          format: int32
        emoji:
          type: string
    One:
      type: object
    Output:
      oneOf:
      - $ref: '#/components/schemas/A1'
    ResultList_camundala.examples.demos.DecisionResultTypes.ManyOutResult[]:
      oneOf:
      - $ref: '#/components/schemas/ManyOutResult'
    SignalMessageExampleIn:
      required:
      - someValue
      type: object
      properties:
        someValue:
          type: string
    SignalMessageExampleOut:
      required:
      - someValue
      - endStatus
      type: object
      properties:
        someValue:
          type: string
        endStatus:
          $ref: '#/components/schemas/EndStatus'
    SimpleEnum:
      oneOf:
      - $ref: '#/components/schemas/One'
      - $ref: '#/components/schemas/Two'
    SimpleObject:
      required:
      - name
      - other
      type: object
      properties:
        name:
          type: string
        other:
          type: boolean
    SingleResult_camundala.examples.demos.DecisionResultTypes.ManyOutResult[]:
      oneOf:
      - $ref: '#/components/schemas/ManyOutResult'
    Two:
      type: object
    messageReceived:
      type: object
    signalReceived:
      type: object
