openapi: 3.1.0
info:
  title: Demos Example Process API
  version: '1.0'
  summary: "\n\nCreated at 09/12/2023, 12:29\n\n**See the [Camundala Documentation](https://pme123.github.io/camundala/)\n\
    \n\n\n\n<details>\n<summary><b><i>CHANGELOG.md</i></b></summary>\n<p>\n\n\nAll\
    \ notable changes to this project will be documented in this file.\n\n* Types\
    \ of Changes (L3):\n  * Added: new features\n  * Changed: changes in existing\
    \ functionality\n  * Deprecated: soon-to-be-removed features\n  * Removed: now\
    \ removed features\n  * Fixed: any bug fixes\n  * Security: in case of vulnerabilities\n\
    \n\nThe format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),\n\
    and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n\
    \n### Unreleased\nInitial Version\n\n</p>\n</details>\n\n\n<p/>\n<details>\n<summary>\n\
    <b><i>Supported General Variables</i></b>\n</summary>\n\n<p>\n\n### Processes\n\
    \n**mockedSubprocesses**:\n\nMock the SubProcesses with their default Mocks.\n\
    This is a list of the _SubProcesses processNames_ you want to mock.\nDepending\
    \ on your implementation it is also possible to use a _comma separated_ String,\n\
    like `\"mySubProcess,myOtherSubProcess\"`\n\n\n- DSL:\n```scala\nprocess(..)\n\
    \  .mockSubProcesses(\"mySubProcess1\", \"mySubProcess2\") // creates a list with\
    \ SubProcessess\n  .mockSubProcess(\"myOtherSubProcess\") // adds a SubProcess\n\
    ```\n\n- Json\n```json\n...\n\"mockedSubprocesses\": [\"mySubProcess\", \"myOtherSubProcess\"\
    ],\n...\n```\n\n### Processes and ExternalTasks\n**outputVariables**:\n\nYou can\
    \ filter the Output with a list of variable names you are interested in.\nThis\
    \ list may include all variables from the output (`Out`). We included an example\
    \ for each Process or ExternalTask.\nDepending on your implementation it is also\
    \ possible to use a _comma separated_ String,\nlike `\"name,firstName\"`\n\n\n\
    - DSL:\n```scala\nprocess(..) // or serviceProcess(..)\n  .withOutputVariables(\"\
    name\", \"firstName\") // creates a list with outputVariables\n  .withOutputVariable(\"\
    nickname\") // adds a outputVariable\n```\n\n- Json\n```json\n...\n\"outputVariables\"\
    : [\"name\", \"firstName\"],\n...\n```\n\n\n**outputMock**:\n\nMock the Process\
    \ or ExternalTask (`Out`)\n - You find an example in every _Process_ and _ExternalTask_.\n\
    \n\n- DSL:\n```scala\nprocess(..) // or serviceProcess(..)\n  .mockWith(outputMock)\n\
    ```\n\n- Json\n```json\n...\n\"outputMock\": {..},\n...\n```\n\n\n**defaultMocked**:\n\
    \nMock the ExternalTasks (Workers only) with their default Mock:\n\n- DSL:\n```scala\n\
    process(..) // or serviceProcess(..)\n  .mockServices\n```\n\n- Json\n```json\n\
    ...\n\"defaultMocked\": true,\n...\n```\n\n\n**impersonateUserId**:\n\nUser-ID\
    \ of a User that should be taken to authenticate to the services.\nThis must be\
    \ supported by your implementation. *Be caution: this may be a security issue!*.\n\
    It is helpful if you have Tokens that expire, but long running Processes.\n\n\
    - DSL:\n```scala\nprocess(..) // or serviceProcess(..)\n  .withImpersonateUserId(impersonateUserId)\n\
    ```\n\n- Json\n```json\n...\n\"impersonateUserId\": \"myUserName\",\n...\n```\n\
    \n### ExternalTasks\n**outputServiceMock**:\n\nMock the Inner-Service (`MockedServiceResponse[ServiceOut]`)\n\
    \ - You find an example in every _ExternalTask_.\n\n\n- DSL:\n```scala\nserviceProcess(..)\n\
    \  .mockServiceWith(MockedServiceResponse\n     .success200(inOut.defaultServiceOutMock))\n\
    ```\n\n- Json\n```json\n...\n\"outputServiceMock\": {\n  \"respStatus\" : 200,\n\
    \  \"respBody\" : \"Example String Body\",\n  \"respHeaders\" : [\n  ]\n},\n...\n\
    ```\n\n\n**handledErrors**:\n\nA list of error codes that are handled (`BpmnError`)\n\
    Depending on your implementation it is also possible to use a _comma separated_\
    \ String,\nlike `\"validation-failed,404\"`\n\n\n- DSL:\n```scala\nserviceProcess(..)\n\
    \  .handleErrors(ErrorCodes.`validation-failed`, \"404\") // create a list of\
    \ handledErrors\n  .handleError(\"404\") // add a handledError\n```\n\n- Json\n\
    ```json\n...\n\"handledErrors\": [\"validation-failed\", \"404\"],\n...\n```\n\
    \n\n**regexHandledErrors**:\n\nYou can further filter Handled Errors with a list\
    \ of Regex expressions that the body error message must match.\nDepending on your\
    \ implementation it is also possible to use a _comma separated_ String,\nlike\
    \ `\"SQL exception,\"errorNr\":\"20000\"\"`\n\n\n- DSL:\n```scala\nserviceProcess(..)\n\
    \  .handleErrorWithRegex(\"SQL exception\")\n  .handleErrorWithRegex(\"\\\"errorNr\\\
    \":\\\"20000\\\"\")\n```\n\n- Json\n```json\n...\n\"regexHandledErrors\": [\"\
    SQL exception\", \"\"errorNr\":\"20000\"\"],\n...\n```\n\n</p>\n</details>\n<p/>\n\
    \        \n"
paths:
  /decisiondmn//singleEntry:
    head:
      tags:
      - ''
      summary: 'DecisionDmn: singleEntry'
      description: |2+


        - Input:  `camundala.examples.demos.bpmn.DecisionResultTypes > Input`
        - Output: `camundala.bpmn.SingleEntry`


        <div class="diagramCanvas">
          <div class="diagram" id="DecisionResultTypes-36447">
            <img onLoad="openFromUrl('DecisionResultTypes.dmn', new DmnJS({ container: $('#DecisionResultTypes-36447'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [DecisionResultTypes.dmn](src/main/resources/DecisionResultTypes.dmn)

      operationId: 'DecisionDmn: singleEntry'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              singleEntry:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                - type: integer
                  format: int32
              examples:
                singleEntry:
                  value: 1
  /decisiondmn//collectEntries:
    head:
      tags:
      - ''
      summary: 'DecisionDmn: collectEntries'
      description: |2+


        - Input:  `camundala.examples.demos.bpmn.DecisionResultTypes > Input`
        - Output: `camundala.bpmn.CollectEntries`


        <div class="diagramCanvas">
          <div class="diagram" id="DecisionResultTypes-70338">
            <img onLoad="openFromUrl('DecisionResultTypes.dmn', new DmnJS({ container: $('#DecisionResultTypes-70338'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [DecisionResultTypes.dmn](src/main/resources/DecisionResultTypes.dmn)

      operationId: 'DecisionDmn: collectEntries'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              collectEntries:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                - type: integer
                  format: int32
              examples:
                collectEntries:
                  value:
                  - 1
                  - 2
  /decisiondmn//singleResult:
    head:
      tags:
      - ''
      summary: 'DecisionDmn: singleResult'
      description: |2+


        - Input:  `camundala.examples.demos.bpmn.DecisionResultTypes > Input`
        - Output: `camundala.bpmn.SingleResult`


        <div class="diagramCanvas">
          <div class="diagram" id="DecisionResultTypes-22073">
            <img onLoad="openFromUrl('DecisionResultTypes.dmn', new DmnJS({ container: $('#DecisionResultTypes-22073'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [DecisionResultTypes.dmn](src/main/resources/DecisionResultTypes.dmn)

      operationId: 'DecisionDmn: singleResult'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              singleResult:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleResult_camundala.examples.demos.bpmn.DecisionResultTypes.ManyOutResult[]'
              examples:
                singleResult:
                  value:
                    index: 1
                    emoji: ðŸ¤©
  /decisiondmn//resultList:
    head:
      tags:
      - ''
      summary: 'DecisionDmn: resultList'
      description: |2+


        - Input:  `camundala.examples.demos.bpmn.DecisionResultTypes > Input`
        - Output: `camundala.bpmn.ResultList`


        <div class="diagramCanvas">
          <div class="diagram" id="DecisionResultTypes-34401">
            <img onLoad="openFromUrl('DecisionResultTypes.dmn', new DmnJS({ container: $('#DecisionResultTypes-34401'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [DecisionResultTypes.dmn](src/main/resources/DecisionResultTypes.dmn)

      operationId: 'DecisionDmn: resultList'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              resultList:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultList_camundala.examples.demos.bpmn.DecisionResultTypes.ManyOutResult[]'
              examples:
                resultList:
                  value:
                  - index: 1
                    emoji: ðŸ¤©
                  - index: 2
                    emoji: ðŸ˜‚
  /process/camundala-mapping-example:
    head:
      tags:
      - camundala-mapping-example
      summary: 'Process: camundala-mapping-example'
      description: "\n\n- Input:  `camundala.domain.NoInput`\n- Output: `camundala.domain.NoOutput`\n\
        \n\n<div class=\"diagramCanvas\">\n  <div class=\"diagram\" id=\"mapping-example-34262\"\
        >\n    <img onLoad=\"openFromUrl('mapping-example.bpmn', new BpmnJS({ container:\
        \ $('#mapping-example-34262'), height: '95%', width: '95%' }));\" src=\"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==\"\
        \ />\n  </div>\n</div>\n\nDownload: [mapping-example.bpmn](src/main/resources/mapping-example.bpmn)\n\
        \n<p/>\n\n<details>\n<summary>\n<b><i>General Variable(s)</i></b>\n</summary>\n\
        \n<p>\n\n**outputVariables**:\n\nJust take the variable you need in your process!\n\
        ```json\n...\n\"outputVariables\": \"\",\n...\n```\n\n**outputMock**:\n\n\
        ```json\n...\n\"outputMock\": {\n  \n},\n...\n```\n\n</p>\n</details>\n</p>\n\
        \      "
      operationId: 'Process: camundala-mapping-example'
      responses:
        '200':
          description: ''
  /decisiondmn/camundala-mapping-example/singleEntry:
    head:
      tags:
      - camundala-mapping-example
      summary: 'DecisionDmn: singleEntry'
      description: |2+


        - Input:  `camundala.examples.demos.bpmn.DecisionResultTypes > Input`
        - Output: `camundala.bpmn.SingleEntry`


        <div class="diagramCanvas">
          <div class="diagram" id="DecisionResultTypes-79357">
            <img onLoad="openFromUrl('DecisionResultTypes.dmn', new DmnJS({ container: $('#DecisionResultTypes-79357'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [DecisionResultTypes.dmn](src/main/resources/DecisionResultTypes.dmn)

      operationId: 'DecisionDmn: singleEntry'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              singleEntry:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                - type: integer
                  format: int32
              examples:
                singleEntry:
                  value: 1
  /decisiondmn/camundala-mapping-example/collectEntries:
    head:
      tags:
      - camundala-mapping-example
      summary: 'DecisionDmn: collectEntries'
      description: |2+


        - Input:  `camundala.examples.demos.bpmn.DecisionResultTypes > Input`
        - Output: `camundala.bpmn.CollectEntries`


        <div class="diagramCanvas">
          <div class="diagram" id="DecisionResultTypes-98073">
            <img onLoad="openFromUrl('DecisionResultTypes.dmn', new DmnJS({ container: $('#DecisionResultTypes-98073'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [DecisionResultTypes.dmn](src/main/resources/DecisionResultTypes.dmn)

      operationId: 'DecisionDmn: collectEntries'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              collectEntries:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                - type: integer
                  format: int32
              examples:
                collectEntries:
                  value:
                  - 1
                  - 2
  /decisiondmn/camundala-mapping-example/singleResult:
    head:
      tags:
      - camundala-mapping-example
      summary: 'DecisionDmn: singleResult'
      description: |2+


        - Input:  `camundala.examples.demos.bpmn.DecisionResultTypes > Input`
        - Output: `camundala.bpmn.SingleResult`


        <div class="diagramCanvas">
          <div class="diagram" id="DecisionResultTypes-25845">
            <img onLoad="openFromUrl('DecisionResultTypes.dmn', new DmnJS({ container: $('#DecisionResultTypes-25845'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [DecisionResultTypes.dmn](src/main/resources/DecisionResultTypes.dmn)

      operationId: 'DecisionDmn: singleResult'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              singleResult:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleResult_camundala.examples.demos.bpmn.DecisionResultTypes.ManyOutResult[]'
              examples:
                singleResult:
                  value:
                    index: 1
                    emoji: ðŸ¤©
  /decisiondmn/camundala-mapping-example/resultList:
    head:
      tags:
      - camundala-mapping-example
      summary: 'DecisionDmn: resultList'
      description: |2+


        - Input:  `camundala.examples.demos.bpmn.DecisionResultTypes > Input`
        - Output: `camundala.bpmn.ResultList`


        <div class="diagramCanvas">
          <div class="diagram" id="DecisionResultTypes-41071">
            <img onLoad="openFromUrl('DecisionResultTypes.dmn', new DmnJS({ container: $('#DecisionResultTypes-41071'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [DecisionResultTypes.dmn](src/main/resources/DecisionResultTypes.dmn)

      operationId: 'DecisionDmn: resultList'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            examples:
              resultList:
                value:
                  letter: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultList_camundala.examples.demos.bpmn.DecisionResultTypes.ManyOutResult[]'
              examples:
                resultList:
                  value:
                  - index: 1
                    emoji: ðŸ¤©
                  - index: 2
                    emoji: ðŸ˜‚
  /process/enum-example:
    head:
      tags:
      - enum-example
      summary: 'Process: enum-example'
      description: "\n\n- Input:  `camundala.examples.demos.bpmn.EnumExample > Input\
        \ > A`\n- Output: `camundala.examples.demos.bpmn.EnumExample > Output > A`\n\
        \n\n<div class=\"diagramCanvas\">\n  <div class=\"diagram\" id=\"enum-example-41093\"\
        >\n    <img onLoad=\"openFromUrl('enum-example.bpmn', new BpmnJS({ container:\
        \ $('#enum-example-41093'), height: '95%', width: '95%' }));\" src=\"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==\"\
        \ />\n  </div>\n</div>\n\nDownload: [enum-example.bpmn](src/main/resources/enum-example.bpmn)\n\
        \n<p/>\n\n<details>\n<summary>\n<b><i>General Variable(s)</i></b>\n</summary>\n\
        \n<p>\n\n**outputVariables**:\n\nJust take the variable you need in your process!\n\
        ```json\n...\n\"outputVariables\": \"someOut,intValue,simpleEnum\",\n...\n\
        ```\n\n**outputMock**:\n\n```json\n...\n\"outputMock\": {\n  \"someOut\" :\
        \ \"hello\",\n  \"intValue\" : 12,\n  \"simpleEnum\" : \"One\",\n  \"type\"\
        \ : \"A\"\n},\n...\n```\n\n</p>\n</details>\n</p>\n      "
      operationId: 'Process: enum-example'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input1'
            examples:
              enum-example:
                value:
                  someValue: hello
                  simpleEnum: One
                  customMock:
                    someOut: hello
                    intValue: 12
                    simpleEnum: One
                    type: A
                  type: A
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Output'
              examples:
                enum-example:
                  value:
                    someOut: hello
                    intValue: 12
                    simpleEnum: One
                    type: A
  /decisiondmn//DateExample:
    head:
      tags:
      - ''
      summary: 'DecisionDmn: DateExample'
      description: |2+


        - Input:  `camundala.examples.demos.bpmn.DateExample > Input`
        - Output: `camundala.bpmn.SingleEntry`


        <div class="diagramCanvas">
          <div class="diagram" id="DateExample-56689">
            <img onLoad="openFromUrl('DateExample.dmn', new DmnJS({ container: $('#DateExample-56689'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [DateExample.dmn](src/main/resources/DateExample.dmn)

      operationId: 'DecisionDmn: DateExample'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input2'
            examples:
              DateExample:
                value:
                  inDate: '2013-12-12T12:12:12'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                - type: string
              examples:
                DateExample:
                  value: 2012-12-12T12:12:12.000+0100
  /decisiondmn//VariablesExample:
    head:
      tags:
      - ''
      summary: 'DecisionDmn: VariablesExample'
      description: |2+


        - Input:  `camundala.examples.demos.bpmn.VariablesExample > Input`
        - Output: `camundala.bpmn.SingleEntry`


        <div class="diagramCanvas">
          <div class="diagram" id="VariablesExample-22514">
            <img onLoad="openFromUrl('VariablesExample.dmn', new DmnJS({ container: $('#VariablesExample-22514'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [VariablesExample.dmn](src/main/resources/VariablesExample.dmn)

      operationId: 'DecisionDmn: VariablesExample'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input3'
            examples:
              VariablesExample:
                value:
                  letters: A_dynamic_2
                  inputVariable: dynamic
                  outputVariable: dynamicOut
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                - type: string
              examples:
                VariablesExample:
                  value: OK dynamicOut
  /process/simulation-TestOverrides:
    head:
      tags:
      - simulation-TestOverrides
      summary: 'Process: simulation-TestOverrides'
      description: "\n\n- Input:  `camundala.examples.demos.bpmn.SimulationTestOverridesExample\
        \ > InOutput`\n- Output: `camundala.examples.demos.bpmn.SimulationTestOverridesExample\
        \ > InOutput`\n\n\n<div class=\"diagramCanvas\">\n  <div class=\"diagram\"\
        \ id=\"simulation-TestOverrides-25892\">\n    <img onLoad=\"openFromUrl('simulation-TestOverrides.bpmn',\
        \ new BpmnJS({ container: $('#simulation-TestOverrides-25892'), height: '95%',\
        \ width: '95%' }));\" src=\"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==\"\
        \ />\n  </div>\n</div>\n\nDownload: [simulation-TestOverrides.bpmn](src/main/resources/simulation-TestOverrides.bpmn)\n\
        \n<p/>\n\n<details>\n<summary>\n<b><i>General Variable(s)</i></b>\n</summary>\n\
        \n<p>\n\n**outputVariables**:\n\nJust take the variable you need in your process!\n\
        ```json\n...\n\"outputVariables\": \"simpleValue,collectionValue,objectValue,objectCollectionValue\"\
        ,\n...\n```\n\n**outputMock**:\n\n```json\n...\n\"outputMock\": {\n  \"simpleValue\"\
        \ : \"hello\",\n  \"collectionValue\" : [\n    \"hello\",\n    \"bye\"\n \
        \ ],\n  \"objectValue\" : {\n    \"name\" : \"salu\",\n    \"other\" : false\n\
        \  },\n  \"objectCollectionValue\" : [\n    {\n      \"name\" : \"salu\",\n\
        \      \"other\" : false\n    },\n    {\n      \"name\" : \"tschau\",\n  \
        \    \"other\" : true\n    }\n  ]\n},\n...\n```\n\n</p>\n</details>\n</p>\n\
        \      "
      operationId: 'Process: simulation-TestOverrides'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InOutput'
            examples:
              simulation-TestOverrides:
                value:
                  simpleValue: hello
                  collectionValue:
                  - hello
                  - bye
                  objectValue:
                    name: salu
                    other: false
                  objectCollectionValue:
                  - name: salu
                    other: false
                  - name: tschau
                    other: true
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InOutput'
              examples:
                simulation-TestOverrides:
                  value:
                    simpleValue: hello
                    collectionValue:
                    - hello
                    - bye
                    objectValue:
                      name: salu
                      other: false
                    objectCollectionValue:
                    - name: salu
                      other: false
                    - name: tschau
                      other: true
  /process/SignalMessageExample/signal-example:
    head:
      tags:
      - SignalMessageExample
      summary: 'Process: signal-example'
      description: "\n\n- Input:  `camundala.examples.demos.bpmn.SignalMessageExample\
        \ > SignalMessageExampleIn`\n- Output: `camundala.examples.demos.bpmn.SignalMessageExample\
        \ > SignalMessageExampleOut`\n\n\n<div class=\"diagramCanvas\">\n  <div class=\"\
        diagram\" id=\"signal-example-42189\">\n    <img onLoad=\"openFromUrl('signal-example.bpmn',\
        \ new BpmnJS({ container: $('#signal-example-42189'), height: '95%', width:\
        \ '95%' }));\" src=\"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==\"\
        \ />\n  </div>\n</div>\n\nDownload: [signal-example.bpmn](src/main/resources/signal-example.bpmn)\n\
        \n<p/>\n\n<details>\n<summary>\n<b><i>General Variable(s)</i></b>\n</summary>\n\
        \n<p>\n\n**outputVariables**:\n\nJust take the variable you need in your process!\n\
        ```json\n...\n\"outputVariables\": \"someValue,endStatus\",\n...\n```\n\n\
        **outputMock**:\n\n```json\n...\n\"outputMock\": {\n  \"someValue\" : \"hello\"\
        ,\n  \"endStatus\" : \"signalReceived\"\n},\n...\n```\n\n</p>\n</details>\n\
        </p>\n      "
      operationId: 'Process: signal-example'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignalMessageExampleIn'
            examples:
              signal-example:
                value:
                  someValue: hello
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignalMessageExampleOut'
              examples:
                signal-example:
                  value:
                    someValue: hello
                    endStatus: signalReceived
  /process/SignalMessageExample/message-for-example:
    head:
      tags:
      - SignalMessageExample
      summary: 'Process: message-for-example'
      description: "\n\n- Input:  `camundala.examples.demos.bpmn.SignalMessageExample\
        \ > SignalMessageExampleIn`\n- Output: `camundala.examples.demos.bpmn.SignalMessageExample\
        \ > SignalMessageExampleOut`\n\n\n<div class=\"diagramCanvas\">\n  <div class=\"\
        diagram\" id=\"message-for-example-78330\">\n    <img onLoad=\"openFromUrl('message-for-example.bpmn',\
        \ new BpmnJS({ container: $('#message-for-example-78330'), height: '95%',\
        \ width: '95%' }));\" src=\"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==\"\
        \ />\n  </div>\n</div>\n\nDownload: [message-for-example.bpmn](src/main/resources/message-for-example.bpmn)\n\
        \n<p/>\n\n<details>\n<summary>\n<b><i>General Variable(s)</i></b>\n</summary>\n\
        \n<p>\n\n**outputVariables**:\n\nJust take the variable you need in your process!\n\
        ```json\n...\n\"outputVariables\": \"someValue,endStatus\",\n...\n```\n\n\
        **outputMock**:\n\n```json\n...\n\"outputMock\": {\n  \"someValue\" : \"hello\"\
        ,\n  \"endStatus\" : \"messageReceived\"\n},\n...\n```\n\n</p>\n</details>\n\
        </p>\n      "
      operationId: 'Process: message-for-example'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignalMessageExampleIn'
            examples:
              message-for-example:
                value:
                  someValue: hello
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignalMessageExampleOut'
              examples:
                message-for-example:
                  value:
                    someValue: hello
                    endStatus: messageReceived
  /signalevent/SignalMessageExample/intermediate-signal-for-example:
    head:
      tags:
      - SignalMessageExample
      summary: 'SignalEvent: intermediate-signal-for-example'
      description: |-
        - _messageName_: `intermediate-signal-for-example`

        - Input:  `camundala.examples.demos.bpmn.SignalMessageExample > SignalMessageExampleIn`
        - Output: `camundala.domain.NoOutput`
      operationId: 'SignalEvent: intermediate-signal-for-example'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignalMessageExampleIn'
            examples:
              intermediate-signal-for-example:
                value:
                  someValue: hello
        required: true
      responses:
        '200':
          description: ''
  /messageevent/SignalMessageExample/intermediate-message-for-example:
    head:
      tags:
      - SignalMessageExample
      summary: 'MessageEvent: intermediate-message-for-example'
      description: |-
        - _messageName_: `intermediate-message-for-example`

        - Input:  `camundala.examples.demos.bpmn.SignalMessageExample > SignalMessageExampleIn`
        - Output: `camundala.domain.NoOutput`
      operationId: 'MessageEvent: intermediate-message-for-example'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignalMessageExampleIn'
            examples:
              intermediate-message-for-example:
                value:
                  someValue: hello
        required: true
      responses:
        '200':
          description: ''
  /process/timer-example:
    head:
      tags:
      - timer-example
      summary: 'Process: timer-example'
      description: "\n\n- Input:  `camundala.domain.NoInput`\n- Output: `camundala.domain.NoOutput`\n\
        \n\n<div class=\"diagramCanvas\">\n  <div class=\"diagram\" id=\"timer-example-21951\"\
        >\n    <img onLoad=\"openFromUrl('timer-example.bpmn', new BpmnJS({ container:\
        \ $('#timer-example-21951'), height: '95%', width: '95%' }));\" src=\"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==\"\
        \ />\n  </div>\n</div>\n\nDownload: [timer-example.bpmn](src/main/resources/timer-example.bpmn)\n\
        \n<p/>\n\n<details>\n<summary>\n<b><i>General Variable(s)</i></b>\n</summary>\n\
        \n<p>\n\n**outputVariables**:\n\nJust take the variable you need in your process!\n\
        ```json\n...\n\"outputVariables\": \"\",\n...\n```\n\n**outputMock**:\n\n\
        ```json\n...\n\"outputMock\": {\n  \n},\n...\n```\n\n</p>\n</details>\n</p>\n\
        \      "
      operationId: 'Process: timer-example'
      responses:
        '200':
          description: ''
  /timerevent/timer-example/wait%20for%20one%20day:
    head:
      tags:
      - timer-example
      summary: 'TimerEvent: wait for one day'
      description: |2-


        - Input:  `camundala.domain.NoInput`
        - Output: `camundala.domain.NoOutput`
      operationId: 'TimerEvent: wait for one day'
      responses:
        '200':
          description: ''
components:
  schemas:
    A:
      required:
      - simpleEnum
      type: object
      properties:
        someValue:
          type: string
        simpleEnum:
          $ref: '#/components/schemas/SimpleEnum'
        customMock:
          $ref: '#/components/schemas/Output'
    A1:
      required:
      - intValue
      - simpleEnum
      type: object
      properties:
        someOut:
          type: string
        intValue:
          type: integer
          format: int32
        simpleEnum:
          $ref: '#/components/schemas/SimpleEnum'
    EndStatus:
      type: string
      enum:
      - messageReceived
      - signalReceived
    InOutput:
      required:
      - simpleValue
      - objectValue
      type: object
      properties:
        simpleValue:
          type: string
        collectionValue:
          type: array
          items:
            type: string
        objectValue:
          $ref: '#/components/schemas/SimpleObject'
        objectCollectionValue:
          type: array
          items:
            $ref: '#/components/schemas/SimpleObject'
    Input:
      required:
      - letter
      type: object
      properties:
        letter:
          type: string
    Input1:
      oneOf:
      - $ref: '#/components/schemas/A'
    Input2:
      required:
      - inDate
      type: object
      properties:
        inDate:
          type: string
    Input3:
      required:
      - inputVariable
      - outputVariable
      type: object
      properties:
        letters:
          type: string
        inputVariable:
          oneOf:
          - type: string
        outputVariable:
          oneOf:
          - type: string
    ManyOutResult:
      required:
      - index
      - emoji
      type: object
      properties:
        index:
          type: integer
          format: int32
        emoji:
          type: string
    Output:
      oneOf:
      - $ref: '#/components/schemas/A1'
    ResultList_camundala.examples.demos.bpmn.DecisionResultTypes.ManyOutResult[]:
      oneOf:
      - $ref: '#/components/schemas/ManyOutResult'
    SignalMessageExampleIn:
      required:
      - someValue
      type: object
      properties:
        someValue:
          type: string
    SignalMessageExampleOut:
      required:
      - someValue
      - endStatus
      type: object
      properties:
        someValue:
          type: string
        endStatus:
          $ref: '#/components/schemas/EndStatus'
    SimpleEnum:
      type: string
      enum:
      - One
      - Two
    SimpleObject:
      required:
      - name
      - other
      type: object
      properties:
        name:
          type: string
        other:
          type: boolean
    SingleResult_camundala.examples.demos.bpmn.DecisionResultTypes.ManyOutResult[]:
      oneOf:
      - $ref: '#/components/schemas/ManyOutResult'
