openapi: 3.0.3
info:
  title: Invoice Example Process API
  version: '1.0'
  description: "\n\nCreated at 05/11/2022, 11:45\n\n**[Check Project on Cawemo](https://cawemo.com/folders/a76e4b8e-8631-4d20-a8eb-258b000ff88a--camundala)**\n\
    \n> This is the invoice demo application which is shipped with the full distributions\
    \ in Camunda 7.\n\nSee the original [README](https://github.com/camunda/camunda-bpm-platform/tree/master/examples/invoice).\n\
    \nI bundled it here! Just run `InvoiceProcessApplication`.\n\n> This requires\
    \ that **Camunda 8 Standalone** is running -> _https://github.com/camunda/camunda-platform.git_\n\
    \nThis based on this Project: https://github.com/pme123/spring-boot-datakurre-plugins\n\
    \n## Migration BPMN/DMN to Camunda 8\n### Pain Points\n- The Migration Plugin\
    \ did not work for DMNs - I had to adjust the XML manually.\n- Forms can not be\
    \ linked (copy-paste Json of form) (Standalone version).\n- Camunda Property Infos\
    \ Plugin does not work.\n- FEEL is missing _**not** myProperty_ - you need to\
    \ do it _myProperty = false_.\n- CallActivities Input-Mapping were not migrated.\n\
    \n### What did not work\n- Forms in the Start Event\n  - Workaround: Added another\
    \ UserTask \n  - but with this, it is impossible to have Camunda Processes running\
    \ by itself (no other application must be deployed)\n- No files\n  - Workaround:\
    \ only the reference to the file is in the process.\n- Dynamic content in Form\
    \ Texts (FEEL)\n- Datastore / Data object reference have no graphic anymore\n\n\
    ### Cool stuff\n- Some code completion in FEEL expressions\n- Links in the Modeller\
    \ to the documentation\n\n## Migrating Camundala to Camunda 8\nThe work to migrate\
    \ the Example concerning:\n- API Documentation\n- Test Simulation\n- Validation\n\
    \n### API Documentation\nNothing to do here - the API stays the same! \U0001f389\
    \U0001f389\U0001f389\n### Test Simulation\n\n\n\n# Changelog\n\n<details>\n<summary>CHANGELOG.md</summary>\n\
    <p>\n\n\nAll notable changes to this project will be documented in this file.\n\
    \n* Types of Changes (L3):\n  * Added: new features\n  * Changed: changes in existing\
    \ functionality\n  * Deprecated: soon-to-be-removed features\n  * Removed: now\
    \ removed features\n  * Fixed: any bug fixes\n  * Security: in case of vulnerabilities\n\
    \n\nThe format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),\n\
    and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n\
    \n### Unreleased\nInitial Version\n\n</p>\n</details>\n\n"
paths:
  /process/InvoiceReceipt/InvoiceReceiptP/InvoiceReceipt:
    head:
      tags:
      - Invoice Receipt
      summary: 'Process: InvoiceReceiptP'
      description: "\nThis starts the Invoice Receipt Process.\n\n<iframe src=\"https://cawemo.com/embed/e289c19a-8a57-4467-8583-de72a5e57488\"\
        \ style=\"width:100%;height:500px;border:1px solid #ccc\" allowfullscreen></iframe>\n\
        \n\n\n**Used in no other Process.**\n\n<details>\n<summary><b>Uses 1 Project(s)\
        \ (EXPERIMENTAL)</b></summary>\n<p>\n\n\n- _invoice-example_\n   - _[ReviewInvoiceP](No\
        \ URL defined for invoice-example/OpenApi.html#operation/Process:%20ReviewInvoiceP)_\
        \ \n   - _[invoice-assign-approver](No URL defined for invoice-example/OpenApi.html#operation/DecisionDmn:%20invoice-assign-approver)_\
        \ (DMN)\n\n\n\n</p>\n</details>\n"
      operationId: 'Process: InvoiceReceiptP'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceReceipt'
            examples:
              Invoice Receipt:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
                  invoiceDocument:
                    fileName: invoice.pdf
                    ref: processes/invoice.pdf
                    mimeType: application/pdf
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceReceiptCheck'
              examples:
                Invoice Receipt:
                  value:
                    approved: true
                    approverGroups:
                    - accounting
                    - sales
  /decisiondmn/InvoiceReceipt/invoice-assign-approver/InvoiceAssignApproverDMN:
    head:
      tags:
      - Invoice Receipt
      summary: 'DecisionDmn: invoice-assign-approver'
      description: |2

        Decision Table on who must approve the Invoice.

        <iframe src="https://cawemo.com/embed/155ba236-d5d1-42f7-8b56-3e90e0bb98d4" style="width:100%;height:500px;border:1px solid #ccc" allowfullscreen></iframe>



        <details>
        <summary><b>Used in 2 Project(s) (EXPERIMENTAL)</b></summary>
        <p>


        - _camundala_
           - [InvoiceReceiptP](No URL defined for camundala/OpenApi.html#operation/Process:%20InvoiceReceiptP)
           - [invoice](No URL defined for camundala/OpenApi.html#operation/Process:%20invoice)


        - _camundala-dsl_
           - [InvoiceReceiptP](No URL defined for camundala-dsl/OpenApi.html#operation/Process:%20InvoiceReceiptP)
           - [invoice](No URL defined for camundala-dsl/OpenApi.html#operation/Process:%20invoice)




        </p>
        </details>
      operationId: 'DecisionDmn: invoice-assign-approver'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelectApproverGroup'
            examples:
              InvoiceAssignApproverDMN:
                value:
                  amount: 30.0
                  invoiceCategory: Software License Costs
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectEntries_camundala.examples.invoice.domain.ApproverGroup[]'
              examples:
                InvoiceAssignApproverDMN:
                  value:
                  - management
  /usertask/InvoiceReceipt/ApproveInvoiceUT:
    head:
      tags:
      - Invoice Receipt
      summary: 'UserTask: ApproveInvoiceUT'
      description: Approve the invoice (or not).
      operationId: 'UserTask: ApproveInvoiceUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceReceipt'
            examples:
              ApproveInvoiceUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
                  invoiceDocument:
                    fileName: invoice.pdf
                    ref: processes/invoice.pdf
                    mimeType: application/pdf
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApproveInvoice'
              examples:
                ApproveInvoiceUT:
                  value:
                    approved: true
                Invoice approved:
                  value:
                    approved: true
                Invoice NOT approved:
                  value:
                    approved: false
  /usertask/InvoiceReceipt/PrepareBankTransferUT:
    head:
      tags:
      - Invoice Receipt
      summary: 'UserTask: PrepareBankTransferUT'
      description: Prepare the bank transfer in the Financial Accounting System.
      operationId: 'UserTask: PrepareBankTransferUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceReceipt'
            examples:
              PrepareBankTransferUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
                  invoiceDocument:
                    fileName: invoice.pdf
                    ref: processes/invoice.pdf
                    mimeType: application/pdf
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrepareBankTransfer'
              examples:
                PrepareBankTransferUT:
                  value: {}
  /process/InvoiceReceipt/Test%20Enum%20Process/testEnumProcess:
    head:
      tags:
      - Invoice Receipt
      summary: 'Process: Test Enum Process'
      description: |2



        **Used in no other Process.**

        **Uses no other Processes.**
      operationId: 'Process: Test Enum Process'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestEnum'
            examples:
              testEnumProcess:
                value:
                  name: hello
                  type: V1
        required: true
      responses:
        '200':
          description: ''
  /process/ReviewInvoice/ReviewInvoiceP/ReviewInvoice:
    head:
      tags:
      - Review Invoice
      summary: 'Process: ReviewInvoiceP'
      description: |2

        This starts the Review Invoice Process.

        <iframe src="https://cawemo.com/embed/cc9f978a-e98a-4b01-991d-36d682574cda" style="width:100%;height:500px;border:1px solid #ccc" allowfullscreen></iframe>



        <details>
        <summary><b>Used in 2 Project(s) (EXPERIMENTAL)</b></summary>
        <p>


        - _camundala_
           - [InvoiceReceiptP](No URL defined for camundala/OpenApi.html#operation/Process:%20InvoiceReceiptP)


        - _camundala-dsl_
           - [InvoiceReceiptP](No URL defined for camundala-dsl/OpenApi.html#operation/Process:%20InvoiceReceiptP)




        </p>
        </details>

        **Uses no other Processes.**
      operationId: 'Process: ReviewInvoiceP'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceReceipt'
            examples:
              Review Invoice:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
                  invoiceDocument:
                    fileName: invoice.pdf
                    ref: processes/invoice.pdf
                    mimeType: application/pdf
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceReviewed'
              examples:
                Review Invoice:
                  value:
                    clarified: true
  /usertask/ReviewInvoice/AssignReviewerUT:
    head:
      tags:
      - Review Invoice
      summary: 'UserTask: AssignReviewerUT'
      description: Select the Reviewer.
      operationId: 'UserTask: AssignReviewerUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceReceipt'
            examples:
              AssignReviewerUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
                  invoiceDocument:
                    fileName: invoice.pdf
                    ref: processes/invoice.pdf
                    mimeType: application/pdf
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssignedReviewer'
              examples:
                AssignReviewerUT:
                  value:
                    reviewer: John
  /usertask/ReviewInvoice/ReviewInvoiceUT:
    head:
      tags:
      - Review Invoice
      summary: 'UserTask: ReviewInvoiceUT'
      description: Review Invoice and approve.
      operationId: 'UserTask: ReviewInvoiceUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceReceipt'
            examples:
              ReviewInvoiceUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
                  invoiceDocument:
                    fileName: invoice.pdf
                    ref: processes/invoice.pdf
                    mimeType: application/pdf
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceReviewed'
              examples:
                ReviewInvoiceUT:
                  value:
                    clarified: true
                Invoice clarified:
                  value:
                    clarified: true
                Invoice NOT clarified:
                  value:
                    clarified: false
components:
  schemas:
    ApproveInvoice:
      required:
      - approved
      type: object
      properties:
        approved:
          type: boolean
          description: If true, the Boss accepted the Invoice
      description: Every Invoice has to be accepted by the Boss.
    ApproverGroup:
      oneOf:
      - $ref: '#/components/schemas/accounting'
      - $ref: '#/components/schemas/management'
      - $ref: '#/components/schemas/sales'
    AssignedReviewer:
      required:
      - reviewer
      type: object
      properties:
        reviewer:
          type: string
    CollectEntries_camundala.examples.invoice.domain.ApproverGroup[]:
      oneOf:
      - $ref: '#/components/schemas/ApproverGroup'
    FileRefInOut:
      required:
      - fileName
      - ref
      type: object
      properties:
        fileName:
          type: string
        ref:
          type: string
          description: A reference to retrieve the file in your application.
        mimeType:
          type: string
    InvoiceCategory:
      oneOf:
      - $ref: '#/components/schemas/Misc'
      - $ref: '#/components/schemas/Software License Costs'
      - $ref: '#/components/schemas/Travel Expenses'
    InvoiceReceipt:
      required:
      - creditor
      - amount
      - invoiceCategory
      - invoiceNumber
      - invoiceDocument
      type: object
      properties:
        creditor:
          type: string
        amount:
          type: number
          format: double
        invoiceCategory:
          $ref: '#/components/schemas/InvoiceCategory'
        invoiceNumber:
          type: string
        invoiceDocument:
          $ref: '#/components/schemas/FileRefInOut'
      description: Received Invoice that need approval.
    InvoiceReceiptCheck:
      type: object
      properties:
        approved:
          type: boolean
          description: If true, the Boss accepted the Invoice
        clarified:
          type: boolean
          description: Flag that is set by the Reviewer (only set if there was a review).
        approverGroups:
          type: array
          items:
            type: string
          description: The groups selected from the DMN
    InvoiceReviewed:
      required:
      - clarified
      type: object
      properties:
        clarified:
          type: boolean
          description: Flag that is set by the Reviewer
    Misc:
      type: object
      description: There are three possible Categories
    PrepareBankTransfer:
      type: object
      description: Prepares the bank transfer for the invoice. Only readOnly fields
        from the Process.
    SelectApproverGroup:
      required:
      - amount
      - invoiceCategory
      type: object
      properties:
        amount:
          type: number
          format: double
        invoiceCategory:
          $ref: '#/components/schemas/InvoiceCategory'
    Software License Costs:
      type: object
      description: There are three possible Categories
    TestEnum:
      oneOf:
      - $ref: '#/components/schemas/V1'
      - $ref: '#/components/schemas/V2'
    Travel Expenses:
      type: object
      description: There are three possible Categories
    V1:
      required:
      - name
      type: object
      properties:
        name:
          type: string
    V2:
      required:
      - id
      type: object
      properties:
        id:
          type: integer
    accounting:
      type: object
      description: These Groups can approve the invoice.
    management:
      type: object
      description: These Groups can approve the invoice.
    sales:
      type: object
      description: These Groups can approve the invoice.
