openapi: 3.0.3
info:
  title: Invoice Example Process API
  version: '1.0'
  summary: |2+


    Created at 15/04/2023, 08:46

    **[Check Project on Cawemo](https://cawemo.com/folders/a76e4b8e-8631-4d20-a8eb-258b000ff88a--camundala)**

    > This is the invoice demo application which is shipped with the full distributions.

    See the original [README](https://github.com/camunda/camunda-bpm-platform/tree/master/examples/invoice).

    I bundled it here! Just run `InvoiceServletProcessApplication`.

    This based on this Project: https://github.com/pme123/spring-boot-datakurre-plugins


    # Changelog

    <details>
    <summary>CHANGELOG.md</summary>
    <p>


    All notable changes to this project will be documented in this file.

    * Types of Changes (L3):
      * Added: new features
      * Changed: changes in existing functionality
      * Deprecated: soon-to-be-removed features
      * Removed: now removed features
      * Fixed: any bug fixes
      * Security: in case of vulnerabilities


    The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
    and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

    ### Unreleased
    Initial Version

    </p>
    </details>

paths:
  /process/InvoiceReceiptP:
    head:
      tags:
      - InvoiceReceiptP
      summary: 'Process: InvoiceReceiptP'
      description: |2+

        This starts the Invoice Receipt Process.

        <iframe src="https://cawemo.com/embed/e289c19a-8a57-4467-8583-de72a5e57488" style="width:100%;height:500px;border:1px solid #ccc" allowfullscreen></iframe>



      operationId: 'Process: InvoiceReceiptP'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceReceipt'
            examples:
              InvoiceReceiptP:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceReceiptCheck'
              examples:
                InvoiceReceiptP:
                  value:
                    approved: true
  /decisiondmn/InvoiceReceiptP/invoice-assign-approver:
    head:
      tags:
      - InvoiceReceiptP
      summary: 'DecisionDmn: invoice-assign-approver'
      description: |2+

        Decision Table on who must approve the Invoice.

        <iframe src="https://cawemo.com/embed/155ba236-d5d1-42f7-8b56-3e90e0bb98d4" style="width:100%;height:500px;border:1px solid #ccc" allowfullscreen></iframe>



      operationId: 'DecisionDmn: invoice-assign-approver'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelectApproverGroup'
            examples:
              invoice-assign-approver:
                value:
                  amount: 30.0
                  invoiceCategory: Software License Costs
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectEntries_camundala.examples.invoice.domain.ApproverGroup[]'
              examples:
                invoice-assign-approver:
                  value:
                  - management
                budget:
                  value:
                  - management
                day-to-day expense:
                  value:
                  - accounting
                  - sales
  /usertask/InvoiceReceiptP/ApproveInvoiceUT:
    head:
      tags:
      - InvoiceReceiptP
      summary: 'UserTask: ApproveInvoiceUT'
      description: Approve the invoice (or not).
      operationId: 'UserTask: ApproveInvoiceUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceReceipt'
            examples:
              ApproveInvoiceUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApproveInvoice'
              examples:
                ApproveInvoiceUT:
                  value:
                    approved: true
                Invoice approved:
                  value:
                    approved: true
                Invoice NOT approved:
                  value:
                    approved: false
  /usertask/InvoiceReceiptP/PrepareBankTransferUT:
    head:
      tags:
      - InvoiceReceiptP
      summary: 'UserTask: PrepareBankTransferUT'
      description: Prepare the bank transfer in the Financial Accounting System.
      operationId: 'UserTask: PrepareBankTransferUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceReceipt'
            examples:
              PrepareBankTransferUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrepareBankTransfer'
              examples:
                PrepareBankTransferUT:
                  value: {}
  /process/ReviewInvoiceP:
    head:
      tags:
      - ReviewInvoiceP
      summary: 'Process: ReviewInvoiceP'
      description: |2+

        This starts the Review Invoice Process.

        <iframe src="https://cawemo.com/embed/cc9f978a-e98a-4b01-991d-36d682574cda" style="width:100%;height:500px;border:1px solid #ccc" allowfullscreen></iframe>



      operationId: 'Process: ReviewInvoiceP'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceReceipt'
            examples:
              ReviewInvoiceP:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceReviewed'
              examples:
                ReviewInvoiceP:
                  value:
                    clarified: true
  /usertask/ReviewInvoiceP/AssignReviewerUT:
    head:
      tags:
      - ReviewInvoiceP
      summary: 'UserTask: AssignReviewerUT'
      description: Select the Reviewer.
      operationId: 'UserTask: AssignReviewerUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceReceipt'
            examples:
              AssignReviewerUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssignedReviewer'
              examples:
                AssignReviewerUT:
                  value:
                    reviewer: John
  /usertask/ReviewInvoiceP/ReviewInvoiceUT:
    head:
      tags:
      - ReviewInvoiceP
      summary: 'UserTask: ReviewInvoiceUT'
      description: Review Invoice and approve.
      operationId: 'UserTask: ReviewInvoiceUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceReceipt'
            examples:
              ReviewInvoiceUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceReviewed'
              examples:
                ReviewInvoiceUT:
                  value:
                    clarified: true
                Invoice clarified:
                  value:
                    clarified: true
                Invoice NOT clarified:
                  value:
                    clarified: false
  /usertask/UserTasks/ApproveInvoiceUT:
    head:
      tags:
      - User Tasks
      summary: 'UserTask: ApproveInvoiceUT'
      description: Approve the invoice (or not).
      operationId: 'UserTask: ApproveInvoiceUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceReceipt'
            examples:
              ApproveInvoiceUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApproveInvoice'
              examples:
                ApproveInvoiceUT:
                  value:
                    approved: true
                Invoice approved:
                  value:
                    approved: true
                Invoice NOT approved:
                  value:
                    approved: false
  /usertask/UserTasks/PrepareBankTransferUT:
    head:
      tags:
      - User Tasks
      summary: 'UserTask: PrepareBankTransferUT'
      description: Prepare the bank transfer in the Financial Accounting System.
      operationId: 'UserTask: PrepareBankTransferUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceReceipt'
            examples:
              PrepareBankTransferUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrepareBankTransfer'
              examples:
                PrepareBankTransferUT:
                  value: {}
  /usertask/UserTasks/AssignReviewerUT:
    head:
      tags:
      - User Tasks
      summary: 'UserTask: AssignReviewerUT'
      description: Select the Reviewer.
      operationId: 'UserTask: AssignReviewerUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceReceipt'
            examples:
              AssignReviewerUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssignedReviewer'
              examples:
                AssignReviewerUT:
                  value:
                    reviewer: John
  /usertask/UserTasks/ReviewInvoiceUT:
    head:
      tags:
      - User Tasks
      summary: 'UserTask: ReviewInvoiceUT'
      description: Review Invoice and approve.
      operationId: 'UserTask: ReviewInvoiceUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceReceipt'
            examples:
              ReviewInvoiceUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceReviewed'
              examples:
                ReviewInvoiceUT:
                  value:
                    clarified: true
                Invoice clarified:
                  value:
                    clarified: true
                Invoice NOT clarified:
                  value:
                    clarified: false
  /decisiondmn/DMNs/invoice-assign-approver:
    head:
      tags:
      - DMNs
      summary: 'DecisionDmn: invoice-assign-approver'
      description: |2+

        Decision Table on who must approve the Invoice.

        <iframe src="https://cawemo.com/embed/155ba236-d5d1-42f7-8b56-3e90e0bb98d4" style="width:100%;height:500px;border:1px solid #ccc" allowfullscreen></iframe>



      operationId: 'DecisionDmn: invoice-assign-approver'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelectApproverGroup'
            examples:
              invoice-assign-approver:
                value:
                  amount: 30.0
                  invoiceCategory: Software License Costs
              budget:
                value:
                  amount: 30.0
                  invoiceCategory: Software License Costs
              day-to-day expense:
                value:
                  amount: 125.0
                  invoiceCategory: Misc
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectEntries_camundala.examples.invoice.domain.ApproverGroup[]'
              examples:
                invoice-assign-approver:
                  value:
                  - management
                budget:
                  value:
                  - management
                day-to-day expense:
                  value:
                  - accounting
                  - sales
components:
  schemas:
    ApproveInvoice:
      required:
      - approved
      type: object
      properties:
        approved:
          type: boolean
          description: If true, the Boss accepted the Invoice
      description: Every Invoice has to be accepted by the Boss.
    ApproverGroup:
      oneOf:
      - $ref: '#/components/schemas/accounting'
      - $ref: '#/components/schemas/management'
      - $ref: '#/components/schemas/sales'
    AssignedReviewer:
      required:
      - reviewer
      type: object
      properties:
        reviewer:
          type: string
    CollectEntries_camundala.examples.invoice.domain.ApproverGroup[]:
      oneOf:
      - $ref: '#/components/schemas/ApproverGroup'
    InvoiceCategory:
      oneOf:
      - $ref: '#/components/schemas/Misc'
      - $ref: '#/components/schemas/Software License Costs'
      - $ref: '#/components/schemas/Travel Expenses'
    InvoiceReceipt:
      required:
      - creditor
      - amount
      - invoiceCategory
      - invoiceNumber
      type: object
      properties:
        creditor:
          type: string
        amount:
          type: number
          format: double
        invoiceCategory:
          $ref: '#/components/schemas/InvoiceCategory'
        invoiceNumber:
          type: string
        shouldFail:
          type: boolean
          description: You can let the Archive Service fail for testing.
    InvoiceReceiptCheck:
      required:
      - approved
      type: object
      properties:
        approved:
          type: boolean
          description: If true, the Boss accepted the Invoice
        clarified:
          type: boolean
          description: Flag that is set by the Reviewer (only set if there was a review).
    InvoiceReviewed:
      required:
      - clarified
      type: object
      properties:
        clarified:
          type: boolean
          description: Flag that is set by the Reviewer
    Misc:
      type: object
      description: There are three possible Categories
    PrepareBankTransfer:
      type: object
      description: Prepares the bank transfer for the invoice. Only readOnly fields
        from the Process.
    SelectApproverGroup:
      required:
      - amount
      - invoiceCategory
      type: object
      properties:
        amount:
          type: number
          format: double
        invoiceCategory:
          $ref: '#/components/schemas/InvoiceCategory'
    Software License Costs:
      type: object
      description: There are three possible Categories
    Travel Expenses:
      type: object
      description: There are three possible Categories
    accounting:
      type: object
      description: These Groups can approve the invoice.
    management:
      type: object
      description: These Groups can approve the invoice.
    sales:
      type: object
      description: These Groups can approve the invoice.
